---
application:
  name: "codentsmusic"
  project: "MusicBot"
  organization: "QoveryCommunity"
routers:
- name: "main-codentsmusic"
  routes:
  - application_name: "codentsmusic"
    paths:
    - "/*"
